# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: autoblack

on:
  push:
    branches:
      - 'ci_dev'
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [ "self-hosted", "build_host" ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: ~/.local/bin/black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'cclauss@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout
          git commit -am "fixup: Format Python code with Black"
          git push
